### ISSUE TITLE
ImportError: No module named click

### ISSUE THREAD

**Issue by abhsc** [skarppi/icloud_photo_station#11]
Package built just fine and installed to the NAS (DS418play, DSM 6.2.3-25426 Update 2)

I have 2FA on my account and this is the error I received when issuing the command within an SSH session.

```
~$ python /volume1/@appstore/icloud_photo_station/app/icloudpd.py \
>     --username 'itunes_user@domain.com' \
>     --password 'pass' \
>     --auto-delete \
>     --until-found 10 \
>     --download output
Traceback (most recent call last):
  File "/volume1/@appstore/icloud_photo_station/app/icloudpd.py", line 2, in <module>
    from icloudpd.base import main
  File "/volume1/@appstore/icloud_photo_station/app/icloudpd/base.py", line 12, in <module>
    import click
ImportError: No module named click
```

Please advise, as I do not know where to start trying to work around this.

**Comment by abhsc** [comment]
Found the root issue, pip was not found during the build, closing issue
