### ISSUE TITLE
KeyError: 'albumNameEnc' - DMS6

### ISSUE THREAD

**Issue by ADMiNZ** [skarppi/icloud_photo_station#38]
2022-03-20 16:56:19 DEBUG    Authenticating...
Traceback (most recent call last):
  File "/volume1/@appstore/icloud_photo_station/app/icloudpd.py", line 5, in <module>
    main()
  File "/volume1/@appstore/icloud_photo_station/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/volume1/@appstore/icloud_photo_station/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/volume1/@appstore/icloud_photo_station/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/volume1/@appstore/icloud_photo_station/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/volume1/@appstore/icloud_photo_station/app/icloudpd/base.py", line 261, in main
    photos = icloud.photos.albums[album]
  File "/volume1/@appstore/icloud_photo_station/env/lib/python2.7/site-packages/pyicloud_ipd/services/photos.py", line 194, in albums
    folder['fields']['albumNameEnc']['value']).decode('utf-8')
KeyError: 'albumNameEnc'

**Comment by ADMiNZ** [comment]
To solve the problem:

vi /volume1/@appstore/icloud_photo_station/env/lib/python2.7/site-packages/pyicloud_ipd/services/photos.py

Commenting on the lines 193-194:

```
                #folder_name = base64.b64decode(
                    #folder['fields']['albumNameEnc']['value']).decode('utf-8')
```

Add below:

```
try:                   
    folder_name = base64.b64decode(
        folder['fields']['albumNameEnc']['value']).decode('utf-8')
except KeyError:              
    continue
```

Problem solved :)
