### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by trapchik** [skarppi/icloud_photo_station#9]
2020-05-24 12:02:40 INFO     Great, you're all set up. The script can now be run without user interaction until 2SA expires.
You can set up email notifications for when the two-step authentication expires.
(Use --help to view information about SMTP options.)
Traceback (most recent call last):
  File "/volume1/@appstore/icloud_photo_station/app/icloudpd.py", line 5, in <module>
    main()
  File "/volume1/@appstore/icloud_photo_station/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/volume1/@appstore/icloud_photo_station/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/volume1/@appstore/icloud_photo_station/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/volume1/@appstore/icloud_photo_station/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/volume1/@appstore/icloud_photo_station/app/icloudpd/base.py", line 277, in main
    directory = os.path.normpath(directory)
  File "/volume1/@appstore/icloud_photo_station/env/lib/python2.7/posixpath.py", line 335, in normpath
    initial_slashes = path.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

what did I miss please?

**Comment by ediKh3n** [comment]
should specify the path:
python /volume1/@appstore/icloud_photo_station/app/icloudpd.py \
    **--directory '<PATH>'**
    --username '<YOUR ICLOUD USERNAME>' \
    --password '<YOUR ICLOUD PASSWORD>' \
    --auto-delete \
    --until-found 10 \
    --download output

**Comment by skarppi** [comment]
The example in Readme is now fixed with the correct syntax as above.
